### PR TITLE
feat/PinSyntax: Additional Syntax to add Pins in HTML

### PR DESCRIPTION
**Pull request by westarne**
This adds an additional syntax for pins in the HTML code.

Before it was only
```
<img ... onload="clickimagePins(this,[[10,10,'right'],[50,60,'left'],[42,25],[80,80,'top']]) />
```

Now you can additionally use

```
<img ... pins="10, 10, 'right'; 50, 60, 'left'; 42, 25; 80, 80, 'top'" />
```

or

```
<img ... pins="[[10,10,'right'],[50,60,'left'],[42,25],[80,80,'top']]" />
```

This is not only shorter, but also requires less knowledge about the actual JavaScript implementation.
Pins are not necessarily written in the JS Array Syntax but can be separated by ';' without any brackets.

With this change ALL of the above mentioned syntaxes work.

### CODE REVIEW

**Comment by SpaceCafe** [comment]
It would be syntactically correct, if you use `data-pins=""` instead. In addition, it's more easier to use only one possible syntax – I prefer the first one:
``

Apart from that, I appreciate your commit :+1:

**Comment by westarne** [comment]
I didn't know about the `data-*` syntax. But I changed it now. Thank you for the hint.

**Comment by SpaceCafe** [comment]
`data-*` syntax allows you to get attributes on a direct way. Therefore, you should change lines like `element.getAttribute('data-pins'))` to `element.dataset.pins`

**Comment by SpaceCafe** [comment]
Could you remove the alternative syntax from `parsePinCoordinates()` and README?
That should be all :+1:

**Pull request merged**
